"""init

Revision ID: 716446640fe9
Revises:
Create Date: 2025-05-12 15:26:55.015807

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "716446640fe9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS access")
    op.execute("CREATE SCHEMA IF NOT EXISTS relations")
    op.execute("CREATE SCHEMA IF NOT EXISTS rights")
    op.execute("CREATE SCHEMA IF NOT EXISTS users")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("'false'"), nullable=False
        ),
        sa.Column(
            "active_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("inactive_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="rights",
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("'false'"), nullable=False
        ),
        sa.Column(
            "active_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("inactive_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="rights",
    )
    op.create_table(
        "users_core",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="users",
    )
    op.create_table(
        "tokens_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "valid_to",
            sa.DateTime(),
            server_default=sa.text("NOW() + INTERVAL '1 day'"),
            nullable=False,
        ),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.users_core.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="access",
    )
    op.create_table(
        "group_claims",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["claim_id"], ["rights.claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["rights.groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "claim_id"),
        schema="relations",
    )
    op.create_table(
        "user_groups",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["rights.groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.users_core.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
        schema="relations",
    )
    op.create_table(
        "users_personal_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("phone_number", sa.Text(), nullable=True),
        sa.Column("telegram_username", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "language",
            sa.String(length=4),
            server_default=sa.text("'en'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.users_core.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
        schema="users",
    )
    op.create_table(
        "users_security",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("password_salt", sa.Text(), nullable=True),
        sa.Column("ban_message", sa.Text(), nullable=True),
        sa.Column(
            "is_banned", sa.Boolean(), server_default=sa.text("'false'"), nullable=False
        ),
        sa.Column("login_ip", sa.String(length=15), nullable=True),
        sa.Column(
            "login_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("login_at", sa.DateTime(), nullable=True),
        sa.Column("banned_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.users_core.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="users",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_security", schema="users")
    op.drop_table("users_personal_info", schema="users")
    op.drop_table("user_groups", schema="relations")
    op.drop_table("group_claims", schema="relations")
    op.drop_table("tokens_info", schema="access")
    op.drop_table("users_core", schema="users")
    op.drop_table("groups", schema="rights")
    op.drop_table("claims", schema="rights")
    # ### end Alembic commands ###
